### ISSUE TITLE
Pre-built binaries - no binary for Darwin/arm64

### ISSUE THREAD

**Issue by chtmorris** [anoma/namada-trusted-setup#102]
I'm trying to do option three - download the pre-built binaries.

I get the following result:

_Creating binary folder...
Downloading new binary for Darwin/arm64...
No binary for Darwin/arm64._

Any ideas?

**Comment by chtmorris** [comment]
I downloaded from source and have it working. But it might be helpful for others to have this working.

**Comment by grarco** [comment]
Hi @chtmorris! At the moment we don't provide pre-built arm binaries for any OS. If that's the case you can always compile it by following [this](https://github.com/anoma/namada-trusted-setup#1-building-and-contributing-from-source) step
