### ISSUE TITLE
My token is invalid

### ISSUE THREAD

**Issue by Lzggno1** [anoma/namada-trusted-setup#104]
My token comes from my email. But when I first used it, it was really used. Later, I saw my token in Unused tokens of Cohort 8. I don't understand. Why is that? The token originally belongs to me, but it is made public
![image](https://user-images.githubusercontent.com/44811382/204120098-67c38fc8-ca89-49fc-8589-e6bdf8eac089.png)

**Comment by Fraccaman** [comment]
It was a new policy we introduced last week, you can read more about it on [twitter](https://twitter.com/namadanetwork/status/1595843269681897481?s=20&t=OxcRSQfXJA0vD1V7bvjlBQ). We decided to remove that policy and distribute some token via twitter. You can read how to get one [here](https://twitter.com/adrian_brink/status/1597172588131672065).
