### ISSUE TITLE
Refactor repo

### ISSUE THREAD

**Issue by grarco** [anoma/namada-trusted-setup#12]
- Clean repo of all the unused file/folders coming from the original Aleo repo
- Clean `Cargo.toml` files from unused imports
- Restrict the elements imported from `phase1-coordinator` to `phase1-cli` to only the strictly necessary ones by using features
- Eliminate all warnings in compilation
- Add documentation and user guide

**Comment by gnosed** [comment]
Also add Acknowledgement to the forked repo. I don't know if we need to reference also the previously forks of forks

**Comment by gnosed** [comment]
We can basically remove all subfolders minus `phase1-coordinator` and `phase1-cli`. Since we didn't reuse the forked code in `phase1-cli` we don't need to reference the copyrights.
