### ISSUE TITLE
CLI WASM Implementation

### ISSUE THREAD

**Issue by gnosed** [anoma/namada-trusted-setup#14]
- port the CLI rust implementation to WASM

**Comment by grarco** [comment]
Due to the new issue #27 it may now be impossible to rework the dependencies to successfully compile for a wasm target

**Comment by grarco** [comment]
I'll close this issue. We cannot compile the client to `wasm32` unless we remove the communication part with the server that relies on the `socket2` crate which is preventing compilation. 
That would mean exporting to a different crate the `contribute_masp` function to be compiled to wasm. After that, we would need to rewrite the entire `contribute` function from `phase1.rs` in the frontend and call the wasm compiled `contribute_masp` function from there

**Comment by grarco** [comment]
I'll close this issue. We cannot compile the client to `wasm32` unless we remove the communication part with the server that relies on the `socket2` crate which is preventing compilation. 
That would mean exporting to a different crate the `contribute_masp` function to be compiled to wasm. After that, we would need to rewrite the entire `contribute` function from `phase1.rs` in the frontend and call the wasm compiled `contribute_masp` function from there
