### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by donadel01** [anoma/namada-trusted-setup#99]
the error i got in the contribution code.

`thread 'main' panicked at 'ERROR: could not contact the Coordinator, please check the url you provided: Client("<!DOCTYPE html><html><head><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width\"/><meta name=\"description\" content=\"Namada Ceremony\" class=\"jsx-3805556923\"/><link rel=\"icon\" href=\"/favicon.ico\" class=\"jsx-3805556923\"/><title>404: This page could not be found</title><meta name=\"next-head-count\" content=\"5\"/><link rel=\"preconnect\" href=\"/\" crossorigin=\"anonymous\"/><link rel=\"preload\" href=\"/_next/static/css/5062966f6568b23f.css\" as=\"style\"/><link rel=\"stylesheet\" href=\"/_next/static/css/5062966f6568b23f.css\" data-n-g=\"\"/><noscript data-n-css=\"\"></noscript><script defer=\"\" nomodule=\"\" src=\"/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js\"></script><script src=\"/_next/static/chunks/webpack-d38be8d96a62f950.js\" defer=\"\"></script><script src=\"/_next/static/chunks/framework-8c5acb0054140387.js\" defer=\"\"></script><script src=\"/_next/static/chunks/main-9a2ef954a54582b8.js\" defer=\"\"></script><script src=\"/_next/static/chunks/pages/_app-22a895f968eee2e4.js\" defer=\"\"></script><script src=\"/_next/static/chunks/pages/_error-8353112a01355ec2.js\" defer=\"\"></script><script src=\"/_next/static/qkje4ilflWIygQe8bYhb1/_buildManifest.js\" defer=\"\"></script><script src=\"/_next/static/qkje4ilflWIygQe8bYhb1/_ssgManifest.js\" defer=\"\"></script><style id=\"__jsx-3805556923\">html{font-family:'__Space_Grotesk_7b2156', '__Space_Grotesk_Fallback_7b2156'}</style></head><body><div id=\"__next\"><main style=\"width:100%;background-image:url(/BackgroundPattern.svg);background-size:64px\" class=\"_app-page__MainContainer-sc-b2a044b6-0 eVa-DvP\"><div class=\"header-components__HeaderContainer-sc-14498965-0 gtNgRo\"><div class=\"header-components__LeftAlignedSection-sc-14498965-1 jZEbTk\"><div class=\"image-components__ImageContainer-sc-27794caa-0 egHRXU\"><svg width=\"114\" height=\"32\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\" class=\"image-components__StyledImage-sc-27794caa-1 fjtkhB\"><g clip-path=\"url(#logo_svg__a)\" fill=\"#0FF\"><path d=\"M114 0h-9.334v32H114V0ZM101.866 0h-9.335v32h9.335V0ZM89.649 0h-9.335v32h9.335V0ZM72.244 31.677H62.068V10.633h-11.76v21.044H40.137V0h32.107v31.677Z\"></path><path d=\"M56.19 21.272a4.366 4.366 0 0 0 4.369-4.364 4.366 4.366 0 0 0-4.368-4.364 4.366 4.366 0 0 0-4.369 4.364 4.366 4.366 0 0 0 4.369 4.364ZM32.108 31.677H21.93V10.633H10.176v21.044H0V0h32.108v31.677Z\"></path></g><defs><clipPath id=\"logo_svg__a\"><path fill=\"#fff\" d=\"M0 0h114v32H0z\"></path></clipPath></defs></svg></div></div><div class=\"header-components__RightAlignedSection-sc-14498965-2 eOjtpn\"><div class=\"image-components__ImageContainer-sc-27794caa-0 egHRXU\"><svg width=\"71\" height=\"48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\" class=\"image-components__StyledImage-sc-27794caa-1 fjtkhB\"><path d=\"M45.978 25.703h-21.22v21.42h21.22v-21.42ZM21.22 25.703H0v21.42h21.22v-21.42ZM70.736 25.703h-21.22v21.42h21.22v-21.42ZM70.736 0h-21.22v21.42h21.22V0ZM45.978 0h-21.22v21.42h21.22V0ZM21.22 0H0v21.42h21.22V0Z\" fill=\"#0FF\"></path></svg></div></div></div><div style=\"font-family:-apple-system, BlinkMacSystemFont, Roboto, &quot;Segoe UI&quot;, &quot;Fira Sans&quot;, Avenir, &quot;Helvetica Neue&quot;, &quot;Lucida Grande&quot;, sans-serif;height:100vh;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center\"><div><style>\n                body { margin: 0; color: #000; background: #fff; }\n                .next-error-h1 {\n                  border-right: 1px solid rgba(0, 0, 0, .3);\n                }\n\n                @media (prefers-color-scheme: dark) {\n                  body { color: #fff; background: #000; }\n                  .next-error-h1 {\n                    border-right: 1px solid rgba(255, 255, 255, .3);\n                  }\n                }</style><h1 class=\"next-error-h1\" style=\"display:inline-block;margin:0;margin-right:20px;padding:0 23px 0 0;font-size:24px;font-weight:500;vertical-align:top;line-height:49px\">404</h1><div style=\"display:inline-block;text-align:left;line-height:49px;height:49px;vertical-align:middle\"><h2 style=\"font-size:14px;font-weight:normal;line-height:49px;margin:0;padding:0\">This page could not be found.</h2></div></div></div><div class=\"footer-components__FooterContainer-sc-349bc1c6-2 iKEFwr\"><div class=\"footer-components__LeftAlignedSection-sc-349bc1c6-3 Eefsz\"><div class=\"footer-components__Column-sc-349bc1c6-5 footer-components__RightColumns-sc-349bc1c6-6 ioiteQ lexPrn\"><a href=\"https://namada.net\" class=\"footer-components__FooterLink-sc-349bc1c6-10 sdBIE\">Home</a><a href=\"https://blog.namada.net\" class=\"footer-components__FooterLink-sc-349bc1c6-10 sdBIE\">Blog</a><a href=\"https://namada.net\" class=\"footer-components__FooterLink-sc-349bc1c6-10 jyasUJ\">Talks</a><a href=\"https://specs.namada.net\" class=\"footer-components__FooterLink-sc-349bc1c6-10 sdBIE\">Specs</a><a href=\"https://docs.namada.net\" class=\"footer-components__FooterLink-sc-349bc1c6-10 sdBIE\">Docs</a></div><div class=\"footer-components__Column-sc-349bc1c6-5 footer-components__RightColumns-sc-349bc1c6-6 ioiteQ lexPrn\"><a href=\"https://namada.net/trusted-setup.html\" class=\"footer-components__FooterLink-sc-349bc1c6-10 sdBIE\">Trusted setup</a><a class=\"footer-components__FooterLink-sc-349bc1c6-10 jyeinJ\">ceremony</a></div></div><div class=\"footer-components__RightAlignedSection-sc-349bc1c6-4 lkBfMk\"><div class=\"footer-components__Column-sc-349bc1c6-5 ioiteQ\"><div class=\"footer-components__TestnetUpdatesButtonContainer-sc-349bc1c6-0 hshcpr\"><a href=\"https://dev.us7.list-manage.com/subscribe?u=69adafe0399f0f2a434d8924b&amp;id=263f552276\"><button class=\"StyledComponentButton__Button-sc-f4b75b27-0 footer-components__TestnetUpdatesButton-sc-349bc1c6-1 hgmlQZ gUlnSp\">Testnet updates</button></a></div><a class=\"footer-components__FooterLink-sc-349bc1c6-10 sdBIE\"><div class=\"footer-components__SocialsContainer-sc-349bc1c6-8 bJetAK\"><div class=\"footer-components__SocialsButton-sc-349bc1c6-9 hJzOqk\"><div style=\"color:black\" class=\"image-components__ImageContainer-sc-27794caa-0 egHRXU\"><svg width=\"28\" height=\"24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\" class=\"image-components__StyledImage-sc-27794caa-1 fjtkhB\"><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"m13.596 6.384.06 1.038-1.011-.127c-3.682-.487-6.9-2.14-9.63-4.915L1.678 1.003 1.335 2.02C.607 4.287 1.072 6.681 2.59 8.291c.809.89.627 1.017-.77.487-.485-.17-.91-.296-.95-.233-.142.149.344 2.076.728 2.839.526 1.06 1.599 2.097 2.772 2.712l.991.487-1.173.021c-1.133 0-1.173.021-1.052.466.405 1.377 2.003 2.839 3.783 3.475l1.255.444-1.093.678a11.084 11.084 0 0 1-5.422 1.568c-.91.021-1.659.106-1.659.17 0 .211 2.468 1.398 3.905 1.864 4.309 1.377 9.428.784 13.272-1.568 2.73-1.674 5.462-5 6.737-8.22.688-1.716 1.375-4.851 1.375-6.355 0-.975.061-1.102 1.194-2.267.668-.678 1.295-1.42 1.416-1.631.203-.403.182-.403-.85-.043-1.72.636-1.962.551-1.112-.402.627-.678 1.376-1.907 1.376-2.267 0-.063-.304.042-.648.233-.364.212-1.173.53-1.78.72l-1.093.36-.991-.699c-.546-.38-1.315-.805-1.72-.932-1.032-.296-2.61-.254-3.54.085-2.53.953-4.127 3.41-3.945 6.101Z\" fill=\"#0ff\"></path></svg></div></div><div class=\"footer-components__SocialsButton-sc-349bc1c6-9 hJzOqk\"><div class=\"image-components__ImageContainer-sc-27794caa-0 egHRXU\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" class=\"image-components__StyledImage-sc-27794caa-1 fjtkhB\"><path d=\"M24 11.779a2.654 2.654 0 0 0-4.497-1.899c-1.81-1.191-4.259-1.949-6.971-2.046l1.483-4.669 4.016.941-.006.058a2.17 2.17 0 0 0 2.174 2.163c1.198 0 2.172-.97 2.172-2.163a2.171 2.171 0 0 0-4.193-.785l-4.329-1.015a.37.37 0 0 0-.44.249L11.755 7.82c-2.838.034-5.409.798-7.3 2.025a2.643 2.643 0 0 0-1.799-.712A2.654 2.654 0 0 0 0 11.779c0 .97.533 1.811 1.317 2.271a4.716 4.716 0 0 0-.086.857C1.231 18.818 6.039 22 11.95 22s10.72-3.182 10.72-7.093c0-.274-.029-.544-.075-.81A2.633 2.633 0 0 0 24 11.779zM6.776 13.595c0-.868.71-1.575 1.582-1.575.872 0 1.581.707 1.581 1.575s-.709 1.574-1.581 1.574-1.582-.706-1.582-1.574zm9.061 4.669c-.797.793-2.048 1.179-3.824 1.179L12 19.44l-.013.003c-1.777 0-3.028-.386-3.824-1.179a.369.369 0 0 1 0-.523.372.372 0 0 1 .526 0c.65.647 1.729.961 3.298.961l.013.003.013-.003c1.569 0 2.648-.315 3.298-.962a.373.373 0 0 1 .526 0 .37.37 0 0 1 0 .524zm-.189-3.095a1.58 1.58 0 0 1-1.581-1.574c0-.868.709-1.575 1.581-1.575s1.581.707 1.581 1.575-.709 1.574-1.581 1.574z\"></path></svg></div></div></div></a></div></div></div></main></div><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{\"statusCode\":404}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"qkje4ilflWIygQe8bYhb1\",\"nextExport\":true,\"isFallback\":false,\"gip\":true,\"scriptLoader\":[]}</script></body></html>")', phase2-cli/src/bin/namada-ts.rs:644:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by grarco** [comment]
Have you tried running the ClI now?
